#pragma once
namespace Chronos {
/**
 * @brief
 * 与d3d11保持一致
 */
enum DrawTopologyType {
    CHRONOS_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,
    CHRONOS_PRIMITIVE_TOPOLOGY_POINTLIST = 1,
    CHRONOS_PRIMITIVE_TOPOLOGY_LINELIST = 2,
    CHRONOS_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,
    CHRONOS_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,
    CHRONOS_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5,
    CHRONOS_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10,
    CHRONOS_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11,
    CHRONOS_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12,
    CHRONOS_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13,
};
}  // namespace Chronos